# Generated by Django 4.2.7 on 2023-12-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_consulta', models.CharField(max_length=45, verbose_name='Nome da Consulta')),
                ('consulta_sql', models.TextField(verbose_name='Consulta SQL')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(null=True, verbose_name='Data de Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Consulta Ativa')),
                ('view_vinculada', models.CharField(blank=True, max_length=45, null=True, verbose_name='View Vinculada')),
                ('contagem_uso', models.SmallIntegerField(blank=True, null=True, verbose_name='Contagem de Uso da Consulta')),
            ],
        ),
    ]
